### ISSUE TITLE
Improve dataset generator to support complex cases

### ISSUE THREAD

**Issue by geclos** [latitude-dev/latitude-llm#1006]
dataset generator has problems generating csvs with complex jsons in a single column, we could improve the the return type and build the csv on our end to simplify the task:

```
csv:
  type: object
  properties:
    headers:
      type: array
    values:
      type: array
```
