### ISSUE TITLE
Using local and s3 storage in docker compose setup

### ISSUE THREAD

**Issue by Bald1nh0** [latitude-dev/latitude-llm#1026]
Hi!

When using local storage, I encounter the error:

```bash
Cannot write file
```

At the same time, there are no logs in docker-compose, which makes it difficult to understand the root cause of the issue.

Here is my .env configuration for local storage:
```bash
# File storage  
# NOTE: In a Docker environment, the "local" strategy will not work out of the box since  
# multiple containers would need to have access to the same local disk.  
# You can use the "s3" strategy instead or set up a shared volume and point the public files path to it.  
DRIVE_DISK=local # options: local, s3  

# Paths for local storage (optional)  
FILE_STORAGE_ROOT_PATH="/app/storage/files"  
FILE_PUBLIC_PATH="files"  
FILES_STORAGE_PATH="/app/storage/files"  
PUBLIC_FILES_STORAGE_PATH="/app/apps/web/public/files" # Must be inside Next.js public folder 
```

Here is the relevant part of my docker-compose.yml:

```yaml
x-common-service: &common-service
  env_file:
    - .env
  volumes:
    - shared-storage:/app/storage/files
    - shared-storage:/app/apps/web/public/files
  depends_on:
    - db
    - redis
  networks:
    - web

x-web-common: &web-common
  <<: *common-service
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.http.services.web-service.loadbalancer.server.port=8080"
    - "traefik.http.routers.web-http.entrypoints=http"
    - "traefik.http.routers.web-http.service=web-service"
    - "traefik.http.routers.web-http.rule=Host(`app-latitude.${APP_DOMAIN}`)"
    - "traefik.http.routers.web-https.tls.certresolver=letsencryptresolver"
    - "traefik.http.middlewares.web-redirect.redirectscheme.scheme=https"
    - "traefik.http.routers.web-http.middlewares=web-redirect"
    - "traefik.http.routers.web-https.entrypoints=https"
    - "traefik.http.routers.web-https.tls=true"
    - "traefik.http.routers.web-https.rule=Host(`app-latitude.${APP_DOMAIN}`)"
    - "traefik.http.routers.web-https.service=web-service"
  depends_on:
    - db
    - redis

x-gateway-common: &gateway-common
  <<: *common-service
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.http.services.gateway-service.loadbalancer.server.port=8080"
    - "traefik.http.routers.gateway-http.entrypoints=http"
    - "traefik.http.routers.gateway-http.service=gateway-service"
    - "traefik.http.routers.gateway-http.rule=Host(`gateway-latitude.${APP_DOMAIN}`)"
    - "traefik.http.routers.gateway-https.tls.certresolver=letsencryptresolver"
    - "traefik.http.middlewares.gateway-redirect.redirectscheme.scheme=https"
    - "traefik.http.routers.gateway-http.middlewares=gateway-redirect"
    - "traefik.http.routers.gateway-https.entrypoints=https"
    - "traefik.http.routers.gateway-https.tls=true"
    - "traefik.http.routers.gateway-https.rule=Host(`gateway-latitude.${APP_DOMAIN}`)"
    - "traefik.http.routers.gateway-https.service=gateway-service"

x-websockets-common: &websockets-common
  <<: *common-service
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.http.services.websockets-service.loadbalancer.server.port=4002"
    - "traefik.http.routers.websockets-http.entrypoints=http"
    - "traefik.http.routers.websockets-http.service=websockets-service"
    - "traefik.http.routers.websockets-http.rule=Host(`ws-latitude.${APP_DOMAIN}`)"
    - "traefik.http.routers.websockets-https.tls.certresolver=letsencryptresolver"
    - "traefik.http.middlewares.websockets-redirect.redirectscheme.scheme=https"
    - "traefik.http.routers.websockets-http.middlewares=websockets-redirect"
    - "traefik.http.routers.websockets-https.entrypoints=https"
    - "traefik.http.routers.websockets-https.tls=true"
    - "traefik.http.routers.websockets-https.rule=Host(`ws-latitude.${APP_DOMAIN}`)"
    - "traefik.http.routers.websockets-https.service=websockets-service"

services:
  mailpit:
    image: axllent/mailpit
    restart: always
    ports:
      - 8025:8025
      - 1025:1025
    profiles:
      - development

  db:
    image: postgres:15.8
    restart: always
    container_name: latitude-llm-db
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - pgdata:/var/lib/postgresql/data
    networks:
    - web

  redis:
    image: redis
    restart: always
    container_name: latitude-llm-redis
    ports:
      - '6379:6379'
    networks:
    - web

  web:
    <<: *web-common
    image: ghcr.io/latitude-dev/web:latest
    restart: always
    container_name: latitude-llm-web
    platform: linux/amd64

  migrations:
    <<: *common-service
    image: ghcr.io/latitude-dev/migrations:latest
    container_name: latitude-llm-migrations
    platform: linux/amd64
    depends_on:
      - db

  gateway:
    <<: *gateway-common
    image: ghcr.io/latitude-dev/gateway:latest
    restart: always
    container_name: latitude-llm-gateway
    platform: linux/amd64

  workers:
    <<: *common-service
    image: ghcr.io/latitude-dev/workers:latest
    restart: always
    container_name: latitude-llm-workers
    platform: linux/amd64

  websockets:
    <<: *websockets-common
    image: ghcr.io/latitude-dev/websockets:latest
    restart: always
    container_name: latitude-llm-websockets
    platform: linux/amd64

networks:
  web:
    external: true

volumes:
  pgdata:
  shared-storage:
```

Despite mounting shared-storage as a volume, the issue persists.

Could you help me understand why this error occurs and how to resolve it?

### Question about S3 authentication

I understand that I can use AWS_ACCESS_KEY and AWS_ACCESS_SECRET to connect to an S3 bucket. However, in some cases, I don't want to issue separate credentials for writing to the bucket. Instead, I would like to use IAM roles that I can assign to an EC2 instance.

Would it be possible to add support for using IAM roles instead of access keys for authentication? That would be a great improvement!

Thanks!
