### ISSUE TITLE
Support parameters in config

### ISSUE THREAD

**Issue by csansoon** [latitude-dev/latitude-llm#1335]
Support `{{ promptl }}` parameters in config. e.g.:
```yaml
---
provider: openai
model: {{ model }}
---
```

This will add a requirement to resolve parameters in order to obtain the config. This means that, from that moment, the more light-weight `scan` method will not return `config` anymore, and that will only be included into the `compile` method.
