### ISSUE TITLE
Import config attributes from other prompts

### ISSUE THREAD

**Issue by csansoon** [latitude-dev/latitude-llm#1337]
Certain configurations, such as tools, are commonly used across many prompts in the same project. Defining them in a single file and importing them as needed would greatly improve usability in these cases.

An example of how this may look like:
```yaml
---
extends: ./config_file

model: gpt-4o
---
```
(Syntax still WIP)
